### ISSUE TITLE
Reference implementations not working with current Psi4 master

### ISSUE THREAD

**Issue by berquist** [psi4/psi4numpy#71]
Using https://github.com/psi4/psi4/commit/0bffede063407f2aada9fd182faa549ddb1cb344,
```
$ python RHF.py

  Memory set to 476.837 MiB by Python driver.
Traceback (most recent call last):
  File "RHF.py", line 33, in <module>
    """)
  File "/home/eric/data/opt/apps/psi4/git-gnu-openblas/lib/psi4/driver/molutil.py", line 253, in geometry
    molecule = core.Molecule.from_dict(molrec['qm'])
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

**Comment by dgasmith** [comment]
Please update `QCElemental` if you are in Conda `conda update qcelemental -c psi4`.

**Comment by berquist** [comment]
I'm not in conda, so wiping the cached versions in the CMake build directory and reinstalling fixed it.
